[package]
name = "calcit_json"
version = "0.0.15"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2021"

[lib]
name = "calcit_json"
path = "src/lib.rs"
crate-type = ["cdylib"] # Stable C ABI only; do not expose Rust dependency symbols.


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calcit_native_ffi = "0.1.1"
cirru_edn = "0.8.0"
cirru_parser = "0.2.8"
hex = "0.4.3"
json = "0.12.4"
